language: c

os: linux
dist: trusty

notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential bc u-boot-tools gcc-arm-linux-gnueabihf

script:
  - git format-patch -1 --stdout | scripts/checkpatch.pl --ignore FILE_PATH_CHANGES --ignore LONG_LINE --ignore LONG_LINE_STRING --ignore LONG_LINE_COMMENT -
  - export ARCH=arm
  - export CROSS_COMPILE=arm-linux-gnueabihf-
  - make zynq_xcomm_adv7511_defconfig
  - make -j`getconf _NPROCESSORS_ONLN` uImage UIMAGE_LOADADDR=0x8000
  - for file in `ls arch/arm/boot/dts/zynq-*.dts`; do make  `basename $file | sed  -e 's\dts\dtb\g'` || exit 1;done
